### ISSUE TITLE
Specifying a julia project path where JuliaFormatter is installed

### ISSUE THREAD

**Issue by senhalil** [qiaojunfeng/pre-commit-julia-format#2]
Not sure if this would be an heavy-lift but can this hook let the user define a project location where JuliaFormatter is installed (so that julia is called with `--project=path` and JuliaFormatter can be found).

**Comment by qiaojunfeng** [comment]
I released a new version `v0.2.0`, please check the README <https://github.com/qiaojunfeng/pre-commit-julia-format?tab=readme-ov-file#julia-project-path> on how to use it.
